// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViaEventAssociation.Infrastructure.EfcDmPersistence;

#nullable disable

namespace ViaEventAssociation.Infrastructure.EfcDmPersistence.Migrations
{
    [DbContext(typeof(EfcDbContext))]
    partial class EfcDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("DCA_ASSIGNMENT.Core.Domain.Aggregates.Events.ViaEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("EventVisibility")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Visibility");

                    b.Property<int>("MaxGuestNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaxGuestNumber");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("DCA_ASSIGNMENT.Core.Domain.Aggregates.Events.ViaEvent", b =>
                {
                    b.OwnsOne("DCA_ASSIGNMENT.Core.Domain.Common.Values.Event.EventTimes", "Times", b1 =>
                        {
                            b1.Property<Guid>("ViaEventId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("EndDate");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("EndTime");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("StartDate");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("StartTime");

                            b1.HasKey("ViaEventId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("ViaEventId");
                        });

                    b.Navigation("Times");
                });
#pragma warning restore 612, 618
        }
    }
}
